name: Receive Webhook
on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_stats]
jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger main update
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"update_stats"}'
