name: Update Stats
on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_stats, update_details]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Update counters
        env:
          EVENT_TYPE: ${{ github.event.action }}
        run: |
          echo "Event: ${EVENT_TYPE}"
          mkdir -p data
          if [ ! -f data/stats.json ]; then
            echo '{"visites":0,"details":0}' > data/stats.json
          fi
          node <<'EOF'
          const fs=require('fs');
          const path='data/stats.json';
          const e=process.env.EVENT_TYPE || 'update_stats';
          const s=JSON.parse(fs.readFileSync(path,'utf8'));
          if(e==='update_details'){ s.details=(s.details||0)+1; }
          else { s.visites=(s.visites||0)+1; }
          fs.writeFileSync(path, JSON.stringify(s,null,2));
          EOF
          git add data/stats.json
          git commit -m "stats: ${EVENT_TYPE}" || echo "No changes"
          git push
