name: Update Stats
on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_stats]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Increment visits
        run: |
          echo "🔢 Mise à jour du compteur..."
          mkdir -p data
          if [ ! -f data/stats.json ]; then
            echo '{"visites":0,"details":0}' > data/stats.json
          fi
          node <<'EOF'
          const fs=require('fs');
          const path='data/stats.json';
          const stats=JSON.parse(fs.readFileSync(path,'utf8'));
          stats.visites++;
          fs.writeFileSync(path,JSON.stringify(stats,null,2));
          EOF
          git add data/stats.json
          git commit -m "update stats" || echo "Pas de changement"
          git push
