name: Update Stats
on:
  repository_dispatch:
    types: [update_stats, update_details]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Increment visits or details
        run: |
          mkdir -p data
          if [ ! -f data/stats.json ]; then
            echo '{"visites":0,"details":0}' > data/stats.json
          fi
          node <<'EOF'
          const fs=require('fs');
          const path='data/stats.json';
          const stats=JSON.parse(fs.readFileSync(path,'utf8'));
          const ev=process.env.EVENT_TYPE;
          if(ev==='update_stats') stats.visites++;
          else if(ev==='update_details') stats.details++;
          fs.writeFileSync(path,JSON.stringify(stats,null,2));
          EOF
        env:
          EVENT_TYPE: ${{ github.event.action }}

      - name: Commit and push changes
        run: |
          git add data/stats.json
          git commit -m "stats: ${{ github.event.action }}" || echo "Pas de changement"
          git push
